sudo: false

git:
  depth: 1

cache:
  directories:
    - $HOME/.composer/cache

language: php

env:
  global:
    - COVERAGE=0 XDEBUG=0

matrix:
  include:
    - php: hhvm-3.18
      sudo: required
      dist: trusty
      env: LARAVEL='5.4.*' XDEBUG=1
      group: edge
    - php: 5.5.9
      env: LARAVEL='5.1.*'
    - php: 5.5.9
      env: LARAVEL='5.2.*'
    - php: 5.5
      env: LARAVEL='5.1.*'
    - php: 5.5
      env: LARAVEL='5.2.*'
    - php: 5.6
      env: LARAVEL='5.1.*'
    - php: 5.6
      env: LARAVEL='5.2.*'
    - php: 5.6
      env: LARAVEL='5.3.*'
    - php: 5.6
      env: LARAVEL='5.4.*'
    - php: 7.0
      env: LARAVEL='5.1.*'
    - php: 7.0
      env: LARAVEL='5.2.*'
    - php: 7.0
      env: LARAVEL='5.3.*'
    - php: 7.0
      env: LARAVEL='5.4.*'
    - php: 7.0
      env: LARAVEL='5.5.*'
    - php: 7.1
      env: LARAVEL='5.1.*'
    - php: 7.1
      env: LARAVEL='5.2.*'
    - php: 7.1
      env: LARAVEL='5.3.*'
    - php: 7.1
      env: LARAVEL='5.4.*'
    - php: 7.1
      env: LARAVEL='5.5.*'
    - php: 7.2
      env: LARAVEL='5.1.*' XDEBUG=1
    - php: 7.2
      env: LARAVEL='5.2.*' XDEBUG=1
    - php: 7.2
      env: LARAVEL='5.3.*' XDEBUG=1
    - php: 7.2
      env: LARAVEL='5.4.*' XDEBUG=1
    - php: 7.2
      env: COVERAGE=1 LARAVEL='5.5.*' XDEBUG=1
  fast_finish: true
  allow_failures:
        - php: 7.2


before_install:
  - if [[ $XDEBUG = 0 ]]; then phpenv config-rm xdebug.ini; fi
  - travis_retry composer self-update
  - travis_retry composer require "illuminate/contracts:${LARAVEL}" --no-interaction --no-update

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script:
  - if [[ $LARAVEL = '5.1.*' ]]; then composer test:ci -- --exclude-group laravel-5.2; fi
  - if [[ $LARAVEL != '5.1.*' ]]; then composer test:ci; fi

after_success:
  - if [[ $COVERAGE = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi
